{% set name = "ag-ui-protocol" %}
{% set version = "0.1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ag_ui_protocol-{{ version }}.tar.gz
  sha256: b336dfebb5751e9cc2c676a3008a4bce4819004e6f6f8cba73169823564472ae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - pydantic >=2.11.2,<3.0.0

test:
  imports:
    - ag_ui.core
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: 'AG-UI: the Agent-User Interaction Protocol. Bring Agents into Frontend Applications.'
  license: MIT
  license_file: LICENSE
  home: https://github.com/ag-ui-protocol/ag-ui

extra:
  recipe-maintainers:
    - rxm7706
